templates:
  - "templates/redis.template.yml"
  - "templates/web.template.yml"
  - "templates/web.ratelimited.template.yml"
  - "templates/web.socketed.template.yml"

expose:
  #- "8880:80"   # http
  #- "443:443" # https

params:
  db_default_text_search_config: "pg_catalog.english"

env:
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8
  LANGUAGE: en_US.UTF-8
  # DISCOURSE_DEFAULT_LOCALE: en

  DISCOURSE_HOSTNAME: {{DISCOURSE_HOSTNAME}}
  #DOCKER_USE_HOSTNAME: true (default false -> "$hostname-$config")
  DISCOURSE_DEVELOPER_EMAILS: {{DISCOURSE_DEVELOPER_EMAILS}}

  DISCOURSE_SMTP_ADDRESS: {{DISCOURSE_SMTP_ADDRESS}}
  DISCOURSE_SMTP_PORT: {{DISCOURSE_SMTP_PORT}}
  DISCOURSE_SMTP_USER_NAME: {{DISCOURSE_SMTP_USER_NAME}}
  DISCOURSE_SMTP_PASSWORD: {{DISCOURSE_SMTP_PASSWORD}}
  #DISCOURSE_SMTP_ENABLE_START_TLS: true
  DISCOURSE_SMTP_DOMAIN: {{DISCOURSE_SMTP_DOMAIN}}
  DISCOURSE_NOTIFICATION_EMAIL: {{DISCOURSE_NOTIFICATION_EMAIL}}

  ## The http or https CDN address for this Discourse instance (configured to pull)
  ## see https://meta.discourse.org/t/14857 for details
  #DISCOURSE_CDN_URL: https://discourse-cdn.example.com

  ## The maxmind geolocation IP account ID and license key for IP address lookups
  ## see https://meta.discourse.org/t/-/173941 for details
  #DISCOURSE_MAXMIND_ACCOUNT_ID: 123456
  #DISCOURSE_MAXMIND_LICENSE_KEY: 1234567890123456

## The Docker container is stateless; all data is stored in /shared
volumes:
  - volume:
      host: /var/discourse/shared/standalone
      guest: /shared
  - volume:
      host: /var/discourse/shared/standalone/log/var-log
      guest: /var/log


docker_args:
  - '--network dirtbikechina_discourse_net --network caddy_edge'


networks:
  dirtbikechina_discourse_net:
    external: true
  ddy_edge:
    external: true


## Plugins go here
## see https://meta.discourse.org/t/19157 for details
hooks:
  after_code:
    - exec:
        cd: $home/plugins
        cmd:
          - git clone https://github.com/discourse/docker_manager.git

## Any custom commands to run after building
run:
  - exec: echo "Beginning of custom commands"
  ## If you want to set the 'From' email address for your first registration, uncomment and change:
  ## After getting the first signup email, re-comment the line. It only needs to run once.
  #- exec: rails r "SiteSetting.notification_email='info@unconfigured.discourse.org'"
  - exec: echo "End of custom commands"
